language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode

before_install:
  - sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra tidy
  - gem install rake minitest coderay stringex
  - gem install prawn --pre

script: rake test
